import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "Fake Detector",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script
        src="https://kit.fontawesome.com/97ca5b5e4b.js"
        crossorigin="anonymous"
      />
    </html>
  );
}
